spring:
  application:
    name: tanzu-java-web-app
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}/postgres
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: always